"""empty message

Revision ID: 937b6fc8f068
Revises: 9adea4db42f9
Create Date: 2025-06-17 11:11:52.424166

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '937b6fc8f068'
down_revision = '9adea4db42f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fav_artists',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['artist.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'artist_id')
    )
    op.drop_table('fav-artists')
    with op.batch_alter_table('artist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('genre', sa.String(length=120), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artist', schema=None) as batch_op:
        batch_op.drop_column('genre')

    op.create_table('fav-artists',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('artist_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['artist.id'], name='fav-artists_artist_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fav-artists_user_id_fkey'),
    sa.PrimaryKeyConstraint('user_id', name='fav-artists_pkey')
    )
    op.drop_table('fav_artists')
    # ### end Alembic commands ###
